Avoid printing extra new lines at the end of usage
cbeust/jcommander pull request #592
Opened 2024-11-29 22:35 UTC by hogejo

JCommander currently prints (in my examples) two extra empty lines at the end of usage. This makes the usage output look weird in my opinion.

One comes from a new line inserted by `JCommander`, which is not visible in tests, since those use the usage formatter directly.
Another one comes from commands, where the separating empty line was added regardless if there was another command coming.

I initially kept (but fixed) the command separating empty line, but I suggest removing all empty lines. Attached is a PR that removes all empty lines.

If you suggest keeping the empty line between commands, I suggest adding empty lines also after main line usage and options. I made the test code more verbose to see the new style. I also introduced one more test to compare the usage output from `JCommander.usage()` instead of the formatter.

2024-11-30 16:00 UTC, mkarg commented
I think having blank lines between the commands helps the reader, particularly with long lists of options and commands.

2024-12-01 08:37 UTC, hogejo commented
Sure thing. How would you like this formatted then? My proposal is:

```
Usage: <main class> [options] [command] [command options]

  Options:
    -a, --a, --a-parameter
      a parameter
      Default: 0

  Commands:
    one      one command
      Usage: one [options]

        Options:
          -b, --b, --b-parameter
            b parameter
            Default: 0

    two      two command
      Usage: two [options]

        Options:
          -c, --c, --c-parameter
            c parameter
            Default: 0
```

Which adds a blank line before "Options", "Commands" as well us keeping the original blank line before commands (except the first one). This however means, that there is going to be a blank line before "Options" for commands as well.

The original looks like this:

```
Usage: <main class> [options] [command] [command options]
  Options:
    -a, --a, --a-parameter
      a parameter
      Default: 0
  Commands:
    one      one command
      Usage: one [options]
        Options:
          -b, --b, --b-parameter
            b parameter
            Default: 0

    two      two command
      Usage: two [options]
        Options:
          -c, --c, --c-parameter
            c parameter
            Default: 0
```

2024-12-01 09:41 UTC, mkarg commented
> Sure thing. How would you like this formatted then? My proposal is:
> 
> ```
> Usage: <main class> [options] [command] [command options]
> 
>   Options:
>     -a, --a, --a-parameter
>       a parameter
>       Default: 0
> 
>   Commands:
>     one      one command
>       Usage: one [options]
> 
>         Options:
>           -b, --b, --b-parameter
>             b parameter
>             Default: 0
> 
>     two      two command
>       Usage: two [options]
> 
>         Options:
>           -c, --c, --c-parameter
>             c parameter
>             Default: 0
> ```
> 
> Which adds a blank line before "Options", "Commands" as well us keeping the original blank line before commands (except the first one). This however means, that there is going to be a blank line before "Options" for commands as well.

LGTM! ❤️

2024-12-01 11:36 UTC, hogejo commented
Done. Please review and merge at your convenience @mkarg !

2024-12-01 13:04 UTC, mkarg requested changes

2024-12-01 13:04 UTC, mkarg commented on src/test/java/com/beust/jcommander/OutputForwardingConsole.java
> +public class OutputForwardingConsole implements Console {
The name is a bit clumsy. What about `StringBuilderConsole`?

2024-12-01 14:28 UTC, mkarg approved these changes

2024-12-01 14:29 UTC, merged